### PR TITLE
Fix login

### LINKED ISSUE #401: Redirect back to origin route after required authentication
When authenticating, the user should be redirected to the route the user is coming from. Right now, we already redirect to the index page. In addition, the redirect to the SSO provider should happen automatically without manual action.

### PR DESCRIPTION
**Pull request by amolenaar**
# Description

## Current behavior

* When refreshing a page you'll end up on the login page (`/auth`).
* After login you'll end up on the default page ('/').

## New behavior

* When refreshing, you're automatically forwarded to the SSO provider page. This normally results in instant authentication.
* When redirected back, you'll be forwarded to the page you were on before reloading.

Resolves #401

# Testing

Locally, with oauth mock (the mock requires you to provide a new name).

# Checklist

- [x] My code follows the guidelines of this project: [CONTRIBUTING.md](/CONTRIBUTING.md)
- [x] I updated the documentation with the new functionality
- [x] I went through the code and removed all print statements, breakpoints and unused code
- [x] Error handling for all possible scenarios has been implemented
- [x] I've add logging for all relevant operations
- [x] I added the appropriate labels to this PR (enhancement/bug/documentation, effort, priority)

### CODE REVIEW

File: frontend/src/app/general/auth/auth/auth.component.ts [hunk 1]
```diff
@@ -41,8 +41,6 @@ export class AuthComponent implements OnInit {
   }
 
   webSSO() {
-    this.authService.getRedirectURL().subscribe((res) => {
-      window.location.href = res.auth_url;
-    });
+    this.authService.webSSO();
   }
```
Comment (MoritzWeber0) [inline frontend/src/app/general/auth/auth/auth.component.ts:45]: I assume this can be replaces by calling `this.authService.webSSO()` directly.

Comment (amolenaar) [reply frontend/src/app/general/auth/auth/auth.component.ts:45]: I wanted to leave it in, since `webSSO()` is invoked from the html template as well.

Comment (MoritzWeber0) [reply frontend/src/app/general/auth/auth/auth.component.ts:45]: I'd make it public then and replace it in the HTML template as well.

**Review by MoritzWeber0 — APPROVED** [review]

File: frontend/src/app/general/auth/auth/auth.component.ts (hunk 1 above)
Comment (amolenaar) [reply frontend/src/app/general/auth/auth/auth.component.ts:45]: I feel it would be better to use the component as the abstraction level, though. Referencing services directly is a first  step towards the creation of [train wrecks](https://wiki.c2.com/?TrainWreck). It always starts with one...
